// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: high_score.
// - Entity ID: 102019aa91b85b77022945c894ce5b4287c.
// - Entity Version: 102019b065294ad73f3a97c533ff432f357.
// - Task ID: 6938ea0a223a4503a8347a29.
// - Task Root ID: 69210cbddf57190621e0c946.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for HighScoreModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface HighScoreModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  player_name: string;
  score: number;
  level_reached: number;
  time_survived: number;
}

/**
 * ORM class for HighScore entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class HighScoreORM {
  private static instance: HighScoreORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019aa91b85b77022945c894ce5b4287c';
    this.entityName = 'high_score';
    this.entityVersion = '102019b065294ad73f3a97c533ff432f357';
    this.taskId = '6938ea0a223a4503a8347a29';
    this.taskRootId = '69210cbddf57190621e0c946';
  }

  /**
   * Get singleton instance of HighScoreORM
   */
  public static getInstance(): HighScoreORM {
    if (!HighScoreORM.instance) {
      HighScoreORM.instance = new HighScoreORM();
    }
    
    return HighScoreORM.instance;
  }

  /**
   * Get all HighScore records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllHighScore(): Promise<HighScoreModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new HighScore record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertHighScore(data: HighScoreModel[]): Promise<HighScoreModel[]> {
    const structured = data.map((item) => CreateData(HighScoreModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all HighScore records
   */
  async purgeAllHighScore(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List HighScore records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listHighScore(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[HighScoreModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get high_score by Id index
   * This function gets data by index.
   */
  async getHighScoreById(
    id: string,
  ): Promise<HighScoreModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) high_score by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setHighScoreById(
    id: string,
    data: HighScoreModel
  ): Promise<HighScoreModel[]> {
    const index = createIndexId(
      id
    );

    const values = HighScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete high_score by Id index
   */
  async deleteHighScoreById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get high_score by DataCreator index
   * This function gets data by index.
   */
  async getHighScoreByDataCreator(
    data_creator: string,
  ): Promise<HighScoreModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) high_score by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setHighScoreByDataCreator(
    data_creator: string,
    data: HighScoreModel
  ): Promise<HighScoreModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = HighScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete high_score by DataCreator index
   */
  async deleteHighScoreByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get high_score by DataUpdater index
   * This function gets data by index.
   */
  async getHighScoreByDataUpdater(
    data_updater: string,
  ): Promise<HighScoreModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) high_score by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setHighScoreByDataUpdater(
    data_updater: string,
    data: HighScoreModel
  ): Promise<HighScoreModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = HighScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete high_score by DataUpdater index
   */
  async deleteHighScoreByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get high_score by Score index
   * This function gets data by index.
   */
  async getHighScoreByScore(
    score: number,
  ): Promise<HighScoreModel[]> {
    const index = createIndexScore(
      score
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) high_score by Score index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setHighScoreByScore(
    score: number,
    data: HighScoreModel
  ): Promise<HighScoreModel[]> {
    const index = createIndexScore(
      score
    );

    const values = HighScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete high_score by Score index
   */
  async deleteHighScoreByScore(
    score: number
  ): Promise<void> {
    const index = createIndexScore(
      score
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to HighScoreModel data array
   */
  private resultToData(values: Data[]): HighScoreModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return HighScoreModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as HighScoreModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized HighScoreModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is HighScoreModel => item !== null);
  }
}

/**
 * Convert HighScoreModel data to Value array
 */
function HighScoreModelToValues(data: HighScoreModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'player_name', type: DataType.string, defaultValue: '' },
    { key: 'score', type: DataType.number, defaultValue: 0 },
    { key: 'level_reached', type: DataType.number, defaultValue: 0 },
    { key: 'time_survived', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof HighScoreModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to HighScoreModel data
 */
function HighScoreModelFromValues(values: Value[]): HighScoreModel {
  const data: Partial<HighScoreModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'player_name':
        data.player_name = ParseValue(value, DataType.string) as string;
        break;
      case 'score':
        data.score = ParseValue(value, DataType.number) as number;
        break;
      case 'level_reached':
        data.level_reached = ParseValue(value, DataType.number) as number;
        break;
      case 'time_survived':
        data.time_survived = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as HighScoreModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Score fields
 */
function createIndexScore(
  score: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, score, 'score'),
  ];

  return {
    fields: ['score'],
    values
  };
}

export default HighScoreORM;